version: '3.3'
services:
  owncloud:
    build:
      args:
        OWNCLOUD_VERSION: "10.0.6"
      context: .
    environment:
      PHP_DISPLAY_ERRORS: "off"
      PHP_UPLOAD_MAX_FILESIZE: "10M"
      OC_DISABLE_ENSURE_APPS_RIGHT: 'true'
    ports:
      - "3000:80"
  mysql:
    image: mysql:5.7.21
    restart: always
